# Banco de dados
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Health check detalhado apenas no desenvolvimento
management.endpoint.health.show-details=always

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrations
spring.flyway.validate-on-migrate=true
spring.flyway.validate-migration-naming=true
spring.flyway.baseline-on-migrate=false

# Flyway será o único responsável pela estrutura do banco
spring.sql.init.mode=never
