# Banco de dados
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# Não exibir informações internas no health check
management.endpoint.health.show-details=never

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrations
spring.flyway.validate-on-migrate=true
spring.flyway.validate-migration-naming=true
spring.flyway.baseline-on-migrate=false

# Desabilita schema.sql e data.sql
spring.sql.init.mode=never