-- V1: estrutura inicial do banco de dados

CREATE TABLE aluno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(150) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_aluno PRIMARY KEY (id)
);

CREATE TABLE curso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(150) NOT NULL,

    CONSTRAINT pk_curso PRIMARY KEY (id),
    CONSTRAINT uk_curso_nome UNIQUE (nome)
);

CREATE TABLE tipo_documento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(150) NOT NULL,

    CONSTRAINT pk_tipo_documento PRIMARY KEY (id),
    CONSTRAINT uk_tipo_documento_nome UNIQUE (nome)
);

CREATE TABLE status_solicitacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(30) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    responsavel INTEGER,
    finaliza_solicitacao BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_status_solicitacao PRIMARY KEY (id),
    CONSTRAINT uk_status_solicitacao_codigo UNIQUE (codigo)
);

CREATE TABLE solicitacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    aluno_id BIGINT NOT NULL,
    curso_id BIGINT NOT NULL,
    tipo_documento_id BIGINT NOT NULL,
    status_id BIGINT NOT NULL,
    data_solicitacao TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,
    data_alteracao TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,
    data_emissao TIMESTAMP(6) WITHOUT TIME ZONE,
    prioridade VARCHAR(20) NOT NULL DEFAULT 'NORMAL',

    CONSTRAINT pk_solicitacao PRIMARY KEY (id),

    CONSTRAINT fk_solicitacao_aluno
        FOREIGN KEY (aluno_id)
        REFERENCES aluno (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_solicitacao_curso
        FOREIGN KEY (curso_id)
        REFERENCES curso (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_solicitacao_tipo_documento
        FOREIGN KEY (tipo_documento_id)
        REFERENCES tipo_documento (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_solicitacao_status
        FOREIGN KEY (status_id)
        REFERENCES status_solicitacao (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_solicitacao_prioridade
        CHECK (prioridade IN ('URGENTE', 'ALTA', 'NORMAL'))
);

CREATE INDEX idx_aluno_nome
    ON aluno (nome);

CREATE INDEX idx_solicitacao_aluno
    ON solicitacao (aluno_id);

CREATE INDEX idx_solicitacao_curso
    ON solicitacao (curso_id);

CREATE INDEX idx_solicitacao_tipo_documento
    ON solicitacao (tipo_documento_id);

CREATE INDEX idx_solicitacao_status
    ON solicitacao (status_id);

CREATE INDEX idx_solicitacao_data_solicitacao
    ON solicitacao (data_solicitacao);

CREATE INDEX idx_solicitacao_prioridade
    ON solicitacao (prioridade);