-- V3: usuários e perfis de acesso

CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(150) NOT NULL,
    login VARCHAR(50) NOT NULL,
    senha VARCHAR(100) NOT NULL,
    codigo_responsavel INTEGER,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_usuario PRIMARY KEY (id),
    CONSTRAINT uk_usuario_login UNIQUE (login),
    CONSTRAINT uk_usuario_codigo_responsavel UNIQUE (codigo_responsavel)
);

CREATE TABLE usuario_perfil (
    usuario_id BIGINT NOT NULL,
    perfil VARCHAR(20) NOT NULL,

    CONSTRAINT pk_usuario_perfil PRIMARY KEY (usuario_id, perfil),
    CONSTRAINT fk_usuario_perfil_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_usuario_perfil_valores
        CHECK (perfil IN ('ADMIN', 'OPERADOR', 'CONSULTA'))
);

CREATE INDEX idx_usuario_login ON usuario (login);
CREATE INDEX idx_usuario_codigo_responsavel ON usuario (codigo_responsavel);
